email notification Front-end commit
fylein/fyle-qbo-app-2 pull request #144
Opened 2022-07-12 08:34 UTC by DhaaraniCIT

2022-07-12 14:11 UTC, ashwin1111 requested changes

2022-07-12 14:11 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.html
> +        <div *ngIf="advancedSettingsForm.controls.exportScheduleFrequency.value" fxLayout="row" class="cursor-pointer" fxLayoutAlign="end center"
We have a global class named `pointer` for this

2022-07-12 14:11 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.scss
> +  padding-right: 20.9%;
We shouldn't be doing this, can resolve over call

2022-07-12 14:11 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.scss
> +.schedule {
combine with existing class

2022-07-12 14:11 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.scss
> +  &--bottom-name {
let's discuss and resolve all these stylings over a call

2022-07-12 14:11 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +  frequencyIntervals: any[] = [...Array(24).keys()].map(day => {
don't use any

2022-07-12 14:11 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +    var date = {
can return the object directly

2022-07-12 14:11 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +      label: +day+1 === 1 ? +day+1 + ' Hour' : +day+1 + ' Hours',
indent, spacing between +

2022-07-12 14:11 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +  schduleSetting: ScheduleSettings;
typo

2022-07-12 14:11 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +  adminEmails: any[] = [{name: 'fyle', email: 'fyle@fyle.in'}, {name: 'fyle1', email: 'fyle1@fyle.in'}];
Why are we having these dummy values?

2022-07-12 14:11 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +      emails: [['fyle@fyle.in']]
Why are we having this dummy value

2022-07-12 14:11 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +      // This.workspaceService.getScheduleSettings(),
remove commented lines

2022-07-12 14:11 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +      // This.adminEmails = response[4];
remove commented lines

2022-07-12 14:11 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +  open() {
return type,
`open(): void {`
Also, function name to be made more clear

2022-07-12 14:11 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +    const that = this;
not needed

2022-07-12 14:11 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +      that.getSettingsAndSetupForm();
Why do we need to load the whole page again?

2022-07-12 14:11 UTC, ashwin1111 commented on src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
> +    <mat-form-field *ngIf="enableTextsearch" floatLabel="always" appearance="outline" class="configuration--form-field">
move all this to a new component as stated above

2022-07-12 14:11 UTC, ashwin1111 commented on src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
> +                <img src="assets/images/pngs/close.png" alt="" srcset="">
download as svg, alt srcset is not needed

2022-07-12 14:11 UTC, ashwin1111 commented on src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
> +            <img src="assets/images/pngs/close.png" alt="" srcset="">
download as svg, alt srcset is not needed

2022-07-13 06:25 UTC, DhaaraniCIT commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +  adminEmails: any[] = [{name: 'fyle', email: 'fyle@fyle.in'}, {name: 'fyle1', email: 'fyle1@fyle.in'}];
As the api are ready, I use dummy data to check the working of the components

2022-07-13 06:25 UTC, DhaaraniCIT commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +  adminEmails: any[] = [{name: 'fyle', email: 'fyle@fyle.in'}, {name: 'fyle1', email: 'fyle1@fyle.in'}];
Once api are ready i will remove them

2022-07-13 06:29 UTC, DhaaraniCIT commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +      // This.workspaceService.getScheduleSettings(),
Apis are not ready so I have just written the code.

2022-07-13 12:03 UTC, ashwin1111 requested changes

2022-07-13 12:03 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.html
> +          <img class="advanced-settings--add-btn" src="assets/images/svgs/general/add.svg">
this should in the actions folder. Add does not come under a general behavior.

2022-07-13 12:03 UTC, ashwin1111 commented on src/app/shared/components/configuration/configuration-multi-select-field/configuration-multi-select-field.component.html
> +                <img src="assets/images/svgs/general/close.svg">
this should in the actions folder. Close does not come under a general behavior.

2022-07-13 12:03 UTC, ashwin1111 commented on src/app/shared/components/configuration/configuration-multi-select-field/configuration-multi-select-field.component.html
> +            <img src="assets/images/svgs/general/close.svg">
this should in the actions folder. Close does not come under a general behavior.

2022-07-20 10:19 UTC, ashwin1111 commented
@DhaaraniCIT please assign me the review once API PR is approved

2022-07-25 16:26 UTC, ashwin1111 requested changes

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/core/models/configuration/advanced-setting.model.ts
> +  workspaceId?: number;
why is this optional?

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/core/models/configuration/advanced-setting.model.ts
> +  addedEmail?: WorkspaceScheduleEmailOptions
why is this optional?

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/core/models/configuration/advanced-setting.model.ts
> +  value: PaymentSyncDirection | number;
why number?

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/core/services/configuration/advanced-setting.service.ts
> +  postWorkspaceSchedule(data: AdvancedSettingWorkspaceSchedulePost): Observable<WorkspaceSchedule> {
@ashwin1111 to discuss this with @DhaaraniCIT tomo, on a call

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/core/services/configuration/advanced-setting.service.ts
> +  getWorkspaceAdmins(): Observable<[WorkspaceScheduleEmailOptions]> {
isn't this supposed to be `[WorkspaceScheduleEmailOptions[]]`?

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/core/services/configuration/advanced-setting.service.ts
> +  getWorkspaceSchedule(): Observable<WorkspaceSchedule> {
this is not needed, advanced_settings get call would give you this detail

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/core/services/workspace/workspace.service.ts
> +
remove

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/add-email-dialog/add-email-dialog.component.html
> +    Add an email address on which you would like to recieve your integration notification mails.
receive typo

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/add-email-dialog/add-email-dialog.component.html
> +    Add an email address on which you would like to recieve your integration notification mails.
Integration -> I caps

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/add-email-dialog/add-email-dialog.component.scss
> +    padding: 24px 165px 24px 24px;
@ashwin1111 to check this on tomo's call

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/add-email-dialog/add-email-dialog.component.scss
> +    font-weight: 500;
not needed

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/add-email-dialog/add-email-dialog.component.scss
> +    letter-spacing: 0.0016em;
not needed

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/add-email-dialog/add-email-dialog.component.ts
> +
remove this line

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +      emails: [this.advancedSettings.workspace_schedules.emails_selected ? this.advancedSettings.workspace_schedules.emails_selected : null]
shouldn't the else case be `: []` ?

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/add-email-dialog/add-email-dialog.component.ts
> +    if (this.data.selectedEmails) {
`.length`

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/add-email-dialog/add-email-dialog.component.ts
> +      this.data.selectedEmails = [this.form.value.adminEmail, ...this.data.selectedEmails];
use concat for consistency

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/add-email-dialog/add-email-dialog.component.ts
> +    this.settingsService.postWorkspaceSchedule(data).subscribe(() => {
@ashwin1111 to discuss this tomo

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/add-email-dialog/add-email-dialog.component.ts
> +    this.form = this.formBuilder.group({
Do this in a separate function, for consistency

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.scss
> +    padding: 24px 12px 8px 68px;
TODO

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.scss
> +  &--bottom-name {
TODO

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.scss
> +  padding-right: 19.2%;
TODO

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +  scheduleSetting: WorkspaceSchedule;
Where is this used?

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +  adminEmails: WorkspaceScheduleEmailOptions[];
Shouldn't this be `[WorkspaceScheduleEmailOptions[]];` ?

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +      this.scheduleSetting = response[3];
Where is this used?

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +      this.scheduleSetting.additional_email_options.length > 0 ? this.scheduleSetting.additional_email_options.map(mail => this.adminEmails.push(mail)) : '';
Where is this used?

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +      this.adminEmails = response[4];
This should be present in advanced settings GET response

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +      this.advancedSettingService.getWorkspaceAdmins()
this is not needed

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +      this.advancedSettingService.getWorkspaceSchedule(),
this is not needed

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +      this.getSettingsAndSetupForm();
TODO for @ashwin1111 to discuss

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
> -    <div class="configuration--field-label-text-section" [ngClass]="{'configuration-select-field--field-label-text-section-without-img': !iconPath}">
please reset this file completely back, in case if there are no changes

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.scss
> +.selected-email {
remove all these classes, if they are not used in this component

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/email-multi-select-field/email-multi-select-field.component.scss
> +.email-configuration{
Why is this a separate class?

2022-07-25 16:26 UTC, ashwin1111 commented on src/app/shared/components/configuration/email-multi-select-field/email-multi-select-field.component.scss
> +.multiline-mat-option.mat-option {
TODO for @ashwin1111 to check

2022-07-25 16:26 UTC, ashwin1111 commented on src/styles.scss
> +.configuration, .email-configuration {
why not use configuration directly?

2022-07-26 05:30 UTC, DhaaraniCIT commented on src/app/core/models/configuration/advanced-setting.model.ts
> +  value: PaymentSyncDirection | number;
you only told to put like this

2022-07-26 06:09 UTC, DhaaraniCIT commented on src/app/core/services/workspace/workspace.service.ts
> +
Why we should remove this, this is used in all components

2022-07-26 06:33 UTC, ashwin1111 commented on src/app/core/models/configuration/advanced-setting.model.ts
> +  value: PaymentSyncDirection | number;
this is resolved offline

2022-07-26 06:45 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +      this.advancedSettingService.getWorkspaceAdmins()
resolved, discussed offline

2022-07-26 06:46 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +      this.adminEmails = response[4];
resolved

2022-07-26 12:08 UTC, DhaaraniCIT commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +  adminEmails: WorkspaceScheduleEmailOptions[];
WorkspaceScheduleEmailOptions[] is array of WorkspaceScheduleEmailOptions object right

2022-07-27 08:18 UTC, DhaaraniCIT commented on src/app/shared/components/configuration/email-multi-select-field/email-multi-select-field.component.scss
> +.email-configuration{
this to reduce the padding bottom for this component alone

2022-07-27 14:34 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.ts
> +  scheduleSetting: WorkspaceSchedule;
remove this

2022-07-27 14:43 UTC, ashwin1111 approved these changes

2022-07-28 12:53 UTC, ashwin1111 commented
I've approved the PR already

2022-08-05 05:17 UTC, merged