email notification advanced setting changes commit
fylein/fyle-qbo-app-2 pull request #156
Opened 2022-08-08 11:50 UTC by DhaaraniCIT

2022-08-08 14:14 UTC, ashwin1111 requested changes

2022-08-08 14:14 UTC, ashwin1111 commented on src/app/shared/components/configuration/email-multi-select-field/email-multi-select-field.component.scss
> +.align-center{
this would override global styling. add it to a separate class with a different name under the parent class.

2022-08-08 14:14 UTC, ashwin1111 commented on src/app/shared/components/configuration/email-multi-select-field/email-multi-select-field.component.scss
>      font-style: normal;
this is not needed

2022-08-08 14:14 UTC, ashwin1111 commented on src/app/shared/components/configuration/email-multi-select-field/email-multi-select-field.component.scss
>      font-style: normal;
this is not needed

2022-08-08 14:14 UTC, ashwin1111 commented on src/app/shared/components/configuration/email-multi-select-field/email-multi-select-field.component.scss
>      font-style: normal;
this is not needed

2022-08-08 14:14 UTC, ashwin1111 commented on src/app/shared/components/configuration/email-multi-select-field/email-multi-select-field.component.scss
>      font-weight: 400;
this is not needed

2022-08-08 14:14 UTC, ashwin1111 commented on src/app/shared/components/configuration/configuration-toggle-field/configuration-toggle-field.component.scss
> +.configuration--export-field-section{
call it export-schedule-section. Also, add it to the parent class.

2022-08-08 14:14 UTC, ashwin1111 commented on src/app/shared/components/configuration/configuration-toggle-field/configuration-toggle-field.component.html
> +<div *ngIf="iconPath" [formGroup]="form" [ngClass]="formControllerName !== 'exportSchedule' ? 'configuration--field-section': 'configuration--export-field-section'">
rename class

2022-08-08 14:14 UTC, ashwin1111 commented on src/app/shared/components/configuration/advanced-settings/advanced-settings.component.html
> +      <div>
why not remove this div, this doesn't add any value no?

2022-08-09 04:52 UTC, DhaaraniCIT commented on src/app/shared/components/configuration/email-multi-select-field/email-multi-select-field.component.scss
>      font-style: normal;
I removed it

2022-08-09 04:55 UTC, DhaaraniCIT commented on src/app/shared/components/configuration/configuration-toggle-field/configuration-toggle-field.component.scss
> +.configuration--export-field-section{
no parent class here

2022-08-10 07:24 UTC, ashwin1111 approved these changes

2022-08-10 07:24 UTC, ashwin1111 commented on src/app/shared/components/configuration/email-multi-select-field/email-multi-select-field.component.scss
> +  &--no-result{
one space after the name

2022-08-10 07:24 UTC, ashwin1111 commented on src/app/shared/components/configuration/configuration-toggle-field/configuration-toggle-field.component.scss
> +.export-schedule-section{
one space after the name

2022-08-12 06:50 UTC, ashwin1111 approved these changes

2022-08-12 08:07 UTC, merged