Generic mapping and employee mapping changes commite
fylein/fyle-qbo-app-2 pull request #217
Opened 2022-10-10 11:47 UTC by DhaaraniCIT

2022-10-11 13:25 UTC, ashwin1111 commented
please assign back review once testing is ready on staging

2022-10-13 07:43 UTC, ashwin1111 commented
Will review once tested on staging, need not assign review, I can take care of it post testing

2022-10-14 07:00 UTC, ashwin1111 requested changes

2022-10-14 07:00 UTC, ashwin1111 commented on src/app/shared/components/mapping/mapping-table/mapping-table.component.ts
> +    const data = this.mappings.data.filter((value) => value.state === 'MAPPED');
Will review this function in next review once other things are fixed

2022-10-14 07:48 UTC, DhaaraniCIT commented on src/app/shared/components/mapping/mapping-table/mapping-table.component.ts
> +  searchResultHandler(result: any){
there is no type for this, that why i added any

2022-10-17 09:59 UTC, ashwin1111 requested changes

2022-10-17 09:59 UTC, ashwin1111 commented on src/app/shared/components/mapping/mapping-table/mapping-table.component.html
> +          <app-simple-text-search [form]="mappingForm[element.index]"  [isSearchInProgress]="isSearchInProgress" [page]="SimpleSearchPage.MAPPING" [searchType]="SimpleSearchType.SELECT_FIELD" (search
`advancedSearchHandler` instead of `searchResultHandler`

2022-10-17 09:59 UTC, ashwin1111 commented on src/app/shared/components/mapping/mapping-table/mapping-table.component.ts
> +    this.originQboData = this.qboData;
how does this help? if qboData is updated, originQboData will also be updated right? where is originQboData helpful?

2022-10-17 09:59 UTC, ashwin1111 commented on src/app/shared/components/helpers/simple-text-search/simple-text-search.component.ts
> +        debounceTime(1500)
indent is off

2022-10-17 09:59 UTC, ashwin1111 commented on src/app/shared/components/helpers/simple-text-search/simple-text-search.component.ts
> +        ).subscribe((search_term: string) => {
`searchTerm` instead of `search_term`. We should be using camelCasing in app and snake_case in api

2022-10-17 09:59 UTC, ashwin1111 commented on src/app/shared/components/helpers/simple-text-search/simple-text-search.component.ts
> +    if (this.searchType === SimpleSearchType.SELECT_FIELD && this.page === SimpleSearchPage.MAPPING){
can emit this irrespective of page no? only the advance search specific pages would listen to it anyways

2022-10-17 10:34 UTC, DhaaraniCIT commented on src/app/shared/components/mapping/mapping-table/mapping-table.component.ts
> +    if (result && result!=='loading...' && result.length>1){
this is because the search should happen only when the search term length greater than 1.

2022-10-17 10:37 UTC, DhaaraniCIT commented on src/app/shared/components/helpers/simple-text-search/simple-text-search.component.ts
> +      this.searchResult.emit('loading...');
loading... is used to indicate that their is a search happening to the parent component, to show searching in dropdown

2022-10-17 10:39 UTC, DhaaraniCIT commented on src/app/shared/components/mapping/mapping-table/mapping-table.component.ts
> +    this.originQboData = this.qboData;
the ngOninit will not run all time and the qboDate at the point of initialize the component, so originalData will be a original data

2022-10-17 10:53 UTC, DhaaraniCIT commented on src/app/shared/components/helpers/simple-text-search/simple-text-search.component.ts
> +    if (this.searchType === SimpleSearchType.SELECT_FIELD && this.page === SimpleSearchPage.MAPPING){
if i remove the page, the specified operation will take places where select field search type is coming, it ok?

2022-10-17 11:05 UTC, ashwin1111 commented on src/app/shared/components/mapping/mapping-table/mapping-table.component.ts
> +    this.originQboData = this.qboData;
you are assigning the reference of qboData to originQboData. Any changes to qboData will affect originQboData as well no?

2022-10-17 11:07 UTC, ashwin1111 commented on src/app/shared/components/helpers/simple-text-search/simple-text-search.component.ts
> +    if (this.searchType === SimpleSearchType.SELECT_FIELD && this.page === SimpleSearchPage.MAPPING){
there is no operations specified inside this if condition. We are just emitting value to those who listen no? Only mapping page will listen to searchResult emits right?

2022-10-17 11:11 UTC, DhaaraniCIT commented on src/app/shared/components/helpers/simple-text-search/simple-text-search.component.ts
> +    if (this.searchType === SimpleSearchType.SELECT_FIELD && this.page === SimpleSearchPage.MAPPING){
it will not create any error

2022-10-17 11:12 UTC, ashwin1111 commented on src/app/shared/components/helpers/simple-text-search/simple-text-search.component.ts
> +    if (this.searchType === SimpleSearchType.SELECT_FIELD && this.page === SimpleSearchPage.MAPPING){
ah then we can remove it off no? the if condition

2022-10-17 11:17 UTC, DhaaraniCIT commented on src/app/shared/components/mapping/mapping-table/mapping-table.component.ts
> +    this.originQboData = this.qboData;
no, the original data remains same, and it is assigned only once, and not changed when qboDate is changed

2022-10-17 11:37 UTC, DhaaraniCIT commented on src/app/shared/components/helpers/simple-text-search/simple-text-search.component.ts
> +    if (this.searchType === SimpleSearchType.SELECT_FIELD && this.page === SimpleSearchPage.MAPPING){
if the check for page is there the emit need not be emit page other than mapping, other pages

2022-10-17 13:12 UTC, ashwin1111 commented on src/app/shared/components/mapping/mapping-table/mapping-table.component.ts
> +    this.existingQboOptions = this.qboData;
this is not fixed yet, https://fylein.slack.com/archives/C044V7Y4D5G/p1666006975352599?thread_ts=1665999140.866329&cid=C044V7Y4D5G

2022-10-17 13:13 UTC, ashwin1111 commented on src/app/shared/components/helpers/simple-text-search/simple-text-search.component.ts
> +          debounceTime(1000)
https://github.com/fylein/fyle-qbo-app-2/pull/217#discussion_r996841369 this is not fixed yet

2022-10-17 13:13 UTC, ashwin1111 commented on src/app/core/services/misc/mapping.service.ts
> +    if (searchTerm){
indent is off

2022-10-17 13:13 UTC, ashwin1111 commented on src/app/core/services/misc/mapping.service.ts
> +    if (searchTerm){
indent

2022-10-17 13:17 UTC, ashwin1111 commented on src/app/shared/components/helpers/simple-text-search/simple-text-search.component.ts
> +      this.searchResult.emit('loading...');
you already have a bunch of if else block to do API calls, why not use the same for constructing the loading part?

2022-10-17 13:17 UTC, ashwin1111 commented on src/app/shared/components/mapping/mapping-table/mapping-table.component.ts
> +    if (result && result!=='loading...' && result.length>1){
if (result) will take care of that no?

2022-10-17 13:25 UTC, ashwin1111 commented on src/app/shared/components/mapping/mapping-table/mapping-table.component.html
> +        <mat-select placeholder="Select {{ this.destinationType | titlecase | snakeCaseToSpaceCase }}" [value]="mappingForm[element.index]?.value?.destination" (closed)="helperService.clearSearchText
why are we calling this func here, even though we have an else case handling same scenario? https://github.com/fylein/fyle-qbo-app-2/pull/217/files#diff-89a122b5c7ac7ee0ff1f787e750bc3ca685375d6919d7a727ab87830b221f872R96

2022-10-17 13:47 UTC, ashwin1111 commented on src/app/shared/components/mapping/mapping-table/mapping-table.component.ts
> +  prepareQBOOptions(results: DestinationAttribute[]){
will suggest something for this function

2022-10-18 05:37 UTC, DhaaraniCIT commented on src/app/shared/components/mapping/mapping-table/mapping-table.component.html
> +        <mat-select placeholder="Select {{ this.destinationType | titlecase | snakeCaseToSpaceCase }}" [value]="mappingForm[element.index]?.value?.destination" (closed)="helperService.clearSearchText
if the select box is clicked and simply closed only this function will take place

2022-10-18 06:26 UTC, DhaaraniCIT commented on src/app/shared/components/mapping/mapping-table/mapping-table.component.html
> +        <mat-select placeholder="Select {{ this.destinationType | titlecase | snakeCaseToSpaceCase }}" [value]="mappingForm[element.index]?.value?.destination" (closed)="helperService.clearSearchText
this commend is resolved

2022-10-31 05:51 UTC, merged